#!/usr/bin/env python3

import os
import sys
from helpers import get_user_timeline

from analyzer import Analyzer
from termcolor import colored, cprint

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    tweets = get_user_timeline(sys.argv[1])
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            cprint(str(score) + " " + tweet , "green")
        elif score < 0.0:
            cprint(str(score) + " " + tweet , "red")
        else:
            cprint(str(score) + " " + tweet , "yellow")

    

if __name__ == "__main__":
    main()

